// api/index.js — Vercel Serverless Function Entry Point
//
// IMPORTANT: This file is a placeholder committed to git so Vercel's build
// scanner can detect it as a serverless function target BEFORE the build runs.
//
// During deployment, the installCommand in vercel.json runs esbuild and
// OVERWRITES this file with the fully-bundled Express API handler.
//
// DO NOT EDIT this file manually — it is replaced at build time.

